// Display labels for the language IDs accepted by the sync contract.
// Keep telemetry IDs and user-entered names intact in storage and payloads.
const languageDisplayNames: Readonly<Record<string, string>> = {
  other: "Other",
  plaintext: "Plain Text",
  javascript: "JavaScript",
  javascriptreact: "React (JavaScript)",
  typescript: "TypeScript",
  typescriptreact: "React (TypeScript)",
  python: "Python",
  java: "Java",
  c: "C",
  cpp: "C++",
  csharp: "C#",
  go: "Go",
  rust: "Rust",
  ruby: "Ruby",
  php: "PHP",
  swift: "Swift",
  kotlin: "Kotlin",
  scala: "Scala",
  dart: "Dart",
  elixir: "Elixir",
  erlang: "Erlang",
  clojure: "Clojure",
  haskell: "Haskell",
  lua: "Lua",
  perl: "Perl",
  r: "R",
  julia: "Julia",
  matlab: "MATLAB",
  "objective-c": "Objective-C",
  "objective-cpp": "Objective-C++",
  shellscript: "Shell Script",
  powershell: "PowerShell",
  bat: "Batch",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  less: "Less",
  sass: "Sass",
  json: "JSON",
  jsonc: "JSON with Comments",
  yaml: "YAML",
  xml: "XML",
  toml: "TOML",
  markdown: "Markdown",
  mdx: "MDX",
  sql: "SQL",
  graphql: "GraphQL",
  dockerfile: "Dockerfile",
  makefile: "Makefile",
  cmake: "CMake",
  terraform: "Terraform",
  hcl: "HCL",
  vue: "Vue",
  svelte: "Svelte",
  astro: "Astro",
  groovy: "Groovy",
  fsharp: "F#",
  ocaml: "OCaml",
  nim: "Nim",
  zig: "Zig",
  solidity: "Solidity",
  proto: "Protocol Buffers",
  diff: "Diff",
  "git-commit": "Git Commit",
  "git-rebase": "Git Rebase",
  ignore: "Ignore",
  ini: "INI",
  properties: "Properties",
  csv: "CSV",
  latex: "LaTeX",
  tex: "TeX",
  bibtex: "BibTeX",
  assembly: "Assembly",
  verilog: "Verilog",
  vhdl: "VHDL",
  vb: "Visual Basic",
  razor: "Razor",
  handlebars: "Handlebars",
  pug: "Pug",
  coffeescript: "CoffeeScript",
  restructuredtext: "reStructuredText",
};

export function getLanguageDisplayName(name: string): string {
  const trimmed = name.trim();
  const key = trimmed.toLowerCase();

  // Preserve unknown IDs and custom manual labels instead of guessing their casing.
  return Object.hasOwn(languageDisplayNames, key)
    ? languageDisplayNames[key]
    : trimmed;
}
